chore(deps): Rollback update to `logstash-logback-encoder`
Fix an issue where logs are not appearing in Central ELK.

Running Janus locally, we're getting the following error:

```log
Exception in thread "AsyncAppender-Worker-ASYNCSTDOUT" java.lang.NoSuchMethodError: 'java.time.Instant ch.qos.logback.classic.spi.ILoggingEvent.getInstant()'
```

Rolling back fixes this.

Co-authored-by: Natasha Thrale <NovemberTang@users.noreply.github.com>